import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Ensure that the incoming `locale` is valid
  const paramLocale = await params;
  const locale = paramLocale.locale;
  if (!routing.locales.includes(locale as never)) {
    notFound();
  }

  return (
    <>{children}</>
  );
}
